services:
  postgres:
    image: postgres:18-alpine
    container_name: service_flow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: serviceflow
      POSTGRES_PASSWORD: serviceflow123
      POSTGRES_DB: serviceflow_db
    ports:
      - "5432:5432"
    volumes:
      - service_flow_pg_data:/var/lib/postgresql

volumes:
  service_flow_pg_data:

