services:
  app:
    image: node:24.12.0-alpine
    container_name: service
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"
    networks:
      - service_network

networks:
  service_network:
    external: true
    name: service_network
    
